version: '3.3'

services:
  db:
    image: arm64v8/mysql:oracle
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - '3306:3306'